# Frequency Domain Analysis of Linear Systems - Bode Plots

## Learning Outcomes {.unnumbered}

After completing this module, you should be able to:

-   Plot Bode Magnitude and Phase Plots

-   Determine the stability information about the system from gain and phase margins

-   Do Relative stability analysis.

## Bode Plot (Corner Plot) of a Transfer Function

The Bode plot of the function $G(j\omega)$ is comprised of two plots

1.  Amplitude Plot: Plot of the amplitude of $G(j\omega)$ in decibels ($\unit{\decibel}$) versus $\log{\omega}$ or $\omega$ and

2.  Phase Plot: Plot of the phase of $G(j\omega)$ in degrees as a function of $\log{\omega}$ or $\omega$. Note: This is $\log(\cdots)$ and not $\ln(\cdots)$ i.e. $\log_e(\cdots)$.

A bode plot is also known as a corner plot or an asymptotic plot of $G(j\omega)$. These names stem from the fact that the Bode plot can be constructed by using straight-line approximations that are asymptotic to the actual plot.

**Advantages of the Bode Plot**

1.  The magnitude of $G(j\omega)$ in the Bode plot is expressed in decibels, the product and division factors in $G(j\omega)$ become additions and subtractions, respectively. The phase relations are also added and subtracted from each other in a natural way.

2.  The magnitude plot of the Bode plots of most $G(j\omega)$ functions encountered in control systems may be approximated by straight-line segments. This makes the construction of the Bode plot very simple.

### Pole-Zero vs. Bode Notation

Consider the function

$$
    G(s) = \dfrac{K_1(s+z_1)(s+z_2)\cdots(s+z_m)}{s^N(s+p_1)(s+p_2)\cdots(s+p_n)} e^{-T_ds}
$$

where $K_1$ and $T_d$ are real constants, and the $z$'s and the $p$'s may be real or complex (in conjugate pairs) numbers.

Note: The equation above is the preferred form for root-locus construction, because the poles and zeros of $G(s)$ are easily identified.

However, for constructing the Bode plot manually, $G(s)$ is preferably written in the following form:

$$
    G(s) = \dfrac{K(1+T_1s)(1+T_2s)\cdots(1+T_ms)}{s^N(1+T_as)(1+T_bs)\cdots(1+T_ns)} e^{-T_ds}
$$

where $K$ is a real constant, the $T$'s may be real or complex (in conjugate pairs) numbers and $T_d$ is the real time delay.

#### Example

The transfer function

$$
    G(s) = \dfrac{150(s+2)}{s^2(s+3)(s+5)(s+10)}
$$

Can be represented as

$$
\begin{aligned}
    G(s) &= \dfrac{150 \cdot 2(1+0.5s)}{s^2\cdot 3\cdot 5\cdot 10(1+0.333s)(1+0.2s)(1+0.1s)}\\
    &= \dfrac{2(1+0.5s)}{s^2(1+0.333s)(1+0.2s)(1+0.1s)}
\end{aligned}
$$

### Magnitude & Phase Angle

The magnitude of $G(s)$ in $\unit{\decibel}$ and its phase angle $\phi(\omega)$ can be expressed as

$$
\begin{aligned}
    \abs{G(j\omega)}_{dB} &= 20\log_{10}\abs{G(j\omega)} \\
    &= 20\log_{10}\abs{K} + 20\log_{10}\abs{1+j\omega T_1} + \cdots + 20\log_{10}\abs{1+j\omega T_m} \\
    &- 20\log_{10}\abs{j\omega} - 20\log_{10}\abs{1+j\omega T_a} - \cdots - 20\log_{10}\abs{1+j\omega T_n}
\end{aligned}
$$

The phase of $G(j\omega)$ is

$$
\begin{aligned}
    \phi(\omega) &= \angle G(j\omega) = \angle K + \angle (1+j\omega T_1) + \angle (1+j\omega T_2) + \cdots+ \angle (1+j\omega T_m) \\
    &-\SI{90}{\degree}N - \angle(1+j\omega T_a) - \angle(1+j\omega T_b) - \cdots - \angle(1+j\omega T_n)
\end{aligned}
$$

Note: The magnitude and phase angle of the complex factor $1+j\omega T$ is given as:

$$
    \abs{1+j\omega T} = \sqrt{1+\omega^2 T^2}\qand \angle(1+j\omega T) = \tan^{-1}(\omega T)
$$

### Common Factor Types

$G(j\omega)$ can contain just five simple types of factors:

1.  Constant factor: $K$

2.  Poles or zeros at the origin of order $N$: $(j\omega)^{\pm N}$

3.  Poles or zeros at $s=-\dfrac{1}{T}$ of order $q$: $(1+j\omega T)^{\pm q}$

4.  Complex poles and zeros of order $r$: $\left(1+ 2\zeta \dfrac{\omega}{\omega_n} - \dfrac{\omega^2}{\omega_n^2} \right)^{\pm r}$

5.  Pure time delay $e^{-j\omega T_d}$

where $T_d$, $N$, $q$, and $r$ are positive integers.

Once we become familiar with the logarithmic plots of these basic factors, it is possible to utilise them in constructing a composite logarithmic plot for any general form of $G(j\omega)H(j\omega)$ by sketching the curves for each factor and adding or subtracting the individual curves graphically, because adding the logarithms of the gains corresponds to multiplying them together.

## Bode Plot of a Pure Constant

Here, $G(s) = K$

The magnitude of $G(j\omega)$ in $\unit{\decibel}$ is given by

$$
    \abs{G(j\omega)}_{dB} = 20\log_{10}\abs{G(j\omega)} = 20\log_{10}\abs{K} 
$$

The phase angle of $G(j\omega)$ is given by

$$
    \angle G(j\omega) = \angle K = 
    \begin{cases}
        \SI{0}{\degree} & K > 0 \\
        \SI{-180}{\degree} & K < 0
    \end{cases}
$$

### Examples

#### Example 1

Let $G(s)=5$

$$
\begin{aligned}
    \abs{G(j\omega)} &= 5 \\
    \abs{G(j\omega)}_{dB} &= 20\log_{10}\abs{5} = \SI{13.9}{\decibel} \\
    \angle G(j\omega) &= \angle 5 = \SI{0}{\degree}
\end{aligned}
$$

![Bode Plot of $G(s) = 5$]

  [Bode Plot of $G(s) = 5$]: ./figures/constant-1-bode.tex {#fig-bode-plot-constant-1 fig-align="center" fig-width="50%"}

{{< pagebreak >}}

#### Example 2

Let $G(s) = -5$

$$
\begin{aligned}
    \abs{G(j\omega)} &= \abs{-5} \\
    \abs{G(j\omega)}_{dB} &= 20\log_{10}\abs{-5} = \SI{13.9}{\decibel} \\
    \angle G(j\omega) &= \angle -5 = \SI{-90}{\degree}
\end{aligned}
$$

![Bode Plot of $G(s) = -5$]

  [Bode Plot of $G(s) = -5$]: ./figures/constant-2-bode.tex {#fig-bode-plot-constant-2 fig-align="center" fig-width="50%"}

{{< pagebreak >}}

## Bode Plot of a Differentiator

Here, $G(s) = s$ The magnitude of $G(j\omega) = j\omega$ in $\unit{\decibel}$ is given by

$$
\begin{aligned}
    \abs{G(j\omega)}_{dB} &= 20\log_{10}\abs{G(j\omega)} \\
    &= 20\log_{10}\abs{j\omega} = 20\log_{10}(\omega) \; \unit{\decibel}
\end{aligned}
$$

The log-magnitude curve is a straight line with a slope of $\SI{20}{\decibel}$/decade.

The phase angle of $G(j\omega)$ is given by

$$
    \angle G(j\omega) = \angle j\omega = \SI{90}{\degree}
$$

![Bode Plot of $G(s) = s$]

  [Bode Plot of $G(s) = s$]: ./figures/differentiator-bode.tex {#fig-bode-plot-differentiator fig-align="center" fig-width="50%"}

{{< pagebreak >}}

## Bode Plot of an Integrator

Here, $G(s) = \dfrac{1}{s}$ The magnitude of $G(j\omega)$ in $\unit{\decibel}$ is given by

$$
\begin{aligned}
    \abs{G(j\omega)}_{dB} &= 20\log_{10}\abs{G(j\omega)} \\
    &= 20\log_{10}\abs{\dfrac{1}{j\omega}} = 20\log_{10}\left(\dfrac{1}{\omega}\right) \\
    &= -20\log_{10}(\omega) \; \unit{\decibel}
\end{aligned}
$$

The log-magnitude curve is a straight line with a slope of $\SI{-20}{\decibel}$/decade.

The phase angle of $G(j\omega) = \dfrac{1}{j\omega}$ is constant and equal to $\SI{-90}{\degree}$.

$$
    \angle G(j\omega) = \angle \dfrac{1}{j\omega} = \SI{-90}{\degree}
$$

![Bode Plot of $G(s) = \dfrac{1}{s}$]

  [Bode Plot of $G(s) = \dfrac{1}{s}$]: ./figures/integrator-bode.tex {#fig-bode-plot-integrator fig-align="center" fig-width="50%"}

{{< pagebreak >}}

## Bode Plot of a Simple Zero $1+sT$

Here, $G(s) = 1+sT$, where $T$ is a positive real constant.

### Magnitude

The magnitude of $G(j\omega)$ is given by 

$$
\abs{G(j\omega)}_{\unit{\decibel}} = 20\log_{10}\abs{G(j\omega)} = 20\log_{10}\sqrt{1+\omega^2 T^2}
$$

To obtain asymptotic approximations of $\abs{G(j\omega)}_{\unit{\decibel}}$, we consider both very large and very small values of $\omega$.

-   At very low frequencies where $\omega T \ll 1$, $\omega^2 T^2$ is very very small compared to 1 and can be neglected. Hence
    $$
    \abs{G(j\omega)}_{\unit{\decibel}} \cong 20\log_{10} 1 = \SI{0}{\decibel}
    $$

-   At very high frequencies where $\omega T \gg 1$, we can approximate $1+\omega^2 T^2$ by $\omega^2 T^2$. Thus,
    $$
    \abs{G(j\omega)}_{\unit{\decibel}} \cong 20\log_{10} \left(\sqrt{\omega^2 T^2} \right) \cong 20\log_{10}(\omega T)
    $$

Thus, the Bode magnitude plot at the low frequencies (i.e. $\omega T \ll 1$), is the constant $\SI{0}{\decibel}$ line.

The Bode magnitude plot at high frequencies (i.e. $\omega T \gg 1$), is a straight line with a slope of $+\SI{20}{\decibel}$/decade of frequency.

The frequency at which the two straight lines (called asymptotes) meet is called the *corner frequency* or *break frequency* and is given by 

$$
\omega = \dfrac{1}{T}
$$

The corner frequency divides the frequency-response curve into two regions: a curve for the low-frequency region and a curve for the high-frequency region.

Note: The corner frequency is very important in sketching logarithmic frequency-response curves.

![Bode Plot of $G(s) = 1+sT$]

  [Bode Plot of $G(s) = 1+sT$]: ./figures/simple-zero-bode.tex {#fig-bode-plot-simple-zero fig-align="center" fig-width="50%"}

### Phase Angle

The exact phase angle $\phi$ of the factor $1+j\omega T$ is: $\phi =\tan^{-1} \omega T$. 

At zero frequency, the phase angle is $\SI{0}{\degree}$.

At the corner frequency, the phase angle is: $\phi = \tan^{-1} \dfrac{T}{T} = \tan^{-1} 1 = +\SI{45}{\degree}$. 

At infinity, the phase angle becomes $\SI{90}{\degree}$. Since the phase angle is given by an inverse tangent function, the phase angle is skew symmetric about the inflection point at $\phi=+\SI{45}{\degree}$. 

Similar to the magnitude curve, a straight-line approximation can be made for the phase curve. 

Because the phase varies from $\SI{0}{\degree}$ to $\SI{90}{\degree}$, we can draw a line from $\SI{0}{\degree}$ at 1 decade below the corner frequency to $\SI{90}{\degree}$ at 1 decade above the corner frequency. 

The maximum deviation between the straight-line approximation and the actual curve is less than $\SI{6}{\degree}$.

{{< pagebreak >}}

## Bode Plot of a Simple Pole $\dfrac{1}{1+sT}$

Here $G(s) = \dfrac{1}{1+sT}$, where $T$ is a positive real constant.

### Magnitude

The magnitude of $G(j\omega)$ is given by

$$
\abs{G(j\omega)}_{\unit{\decibel}} = 20\log_{10}\abs{G(j\omega)} = -20\log_{10}\sqrt{1+\omega^2 T^2}
$$

To obtain asymptotic approximations of $\abs{G(j\omega)}_{\unit{\decibel}}$, we consider both very large and very small values of $\omega$.

-   At very low frequencies where $\omega T \ll 1$, $\omega^2 T^2$ is very very small compared to 1 and can be neglected. Hence\
    $$
    \abs{G(j\omega)}_{\unit{\decibel}} \cong 20\log_{10} 1 = \SI{0}{\decibel}
    $$
-   At very high frequencies where $\omega T \gg 1$, we can approximate $1+\omega^2 T^2$ by $\omega^2 T^2$. Thus,\
    $$
    \abs{G(j\omega)}_{\unit{\decibel}} \cong -20\log_{10} \left(\sqrt{\omega^2 T^2} \right) \cong -20\log_{10}(\omega T)
    $$

Thus, the Bode magnitude plot at the low frequencies (i.e. $\omega T \ll 1$), is the constant $\SI{0}{\decibel}$ line.

The Bode magnitude plot at high frequencies (i.e. $\omega T \gg 1$), is a straight line with a slope of $\SI{-20}{\decibel}$/decade of frequency.

The frequency at which the two straight lines (called asymptotes) meet is called the *corner frequency* or *break frequency* and is given by 

$$
\omega = \dfrac{1}{T}
$$

The corner frequency divides the frequency-response curve into two regions: a curve for the low-frequency region and a curve for the high-frequency region.

Note: The corner frequency is very important in sketching logarithmic frequency-response curves.

![Bode Plot of $G(s) = \dfrac{1}{1+sT}$]

  [Bode Plot of $G(s) = \dfrac{1}{1+sT}$]: ./figures/simple-pole-bode.tex {#fig-bode-plot-simple-pole fig-align="center" fig-width="50%"}

### Phase Angle

The exact phase angle $\phi$ of the factor $\dfrac{1}{1+j\omega T}$ is: $\phi = -\tan^{-1} \omega T$.

At zero frequency, the phase angle is $\SI{0}{\degree}$.

At the corner frequency, the phase angle is: $\phi = -\tan^{-1} \dfrac{T}{T} = -\tan^{-1} (1) = \SI{-45}{\degree}$. 

At infinity, the phase angle becomes $\SI{-90}{\degree}$. Since the phase angle is given by an inverse tangent function, the phase angle is skew symmetric about the inflection point at $\phi=\SI{-45}{\degree}$. 

Similar to the magnitude curve, a straight-line approximation can be made for the phase curve. 

Because the phase varies from $\SI{0}{\degree}$ to $\SI{-90}{\degree}$, we can draw a line from $\SI{0}{\degree}$ at 1 decade below the corner frequency to $\SI{-90}{\degree}$ at 1 decade above the corner frequency. 

The maximum deviation between the straight-line approximation and the actual curve is less than $\SI{6}{\degree}$.

{{< pagebreak >}}

## Advantages of Approximate Bode Plot using Asymptotes

The asymptotes are quite easy to draw and are sufficiently close to the exact curve.

The use of such approximations in drawing Bode diagrams is convenient in establishing the general nature of the frequency-response characteristics quickly with a minimum amount of calculation and may be used for most preliminary design work.

The actual $\abs{G(j\omega)}\unit{\decibel}$ plot is a smooth curve and deviates only slightly from the straight line approximation.

If accurate frequency-response curves are desired, corrections may easily be made.

The error between the actual magnitude curve and the straight-line asymptotes is symmetrical with respect to the corner frequency $\omega=\dfrac{1}{T}$.

In practice, an accurate frequency-response curve can be drawn by introducing a correction of $\SI{3}{\decibel}$ at the corner frequency and a correction of $\SI{1}{\decibel}$ at points one octave below and above the corner frequency and then connecting these points by a smooth curve.

{{< pagebreak >}}

## Bode Plot of Quadratic Factors

Consider the function

$$
    G(s) = \dfrac{\omega_n^2}{s^2 + 2\zeta\omega_n s + \omega_n^2} = \dfrac{1}{1+\left(\frac{2\zeta}{\omega_n}\right)s + \left(\frac{1}{\omega_n^2}\right)s^2}
$$

We are interested only in the case when $\zeta < 1$, because otherwise $G(s)$ would have two unequal real poles, and the Bode plot can be obtained by considering $G(s)$ as the product of two transfer functions with simple poles. Now by letting $s=j\omega$, the above function can be written as

$$
\begin{aligned}
    G(j\omega) &= \dfrac{1}{1+\left(\frac{2\zeta}{\omega_n} \right)j\omega + \left(\frac{1}{\omega_n^2}\right)(j\omega)^2} = \dfrac{1}{1+j\left(\frac{2\zeta}{\omega_n}\right)\omega - \left(\frac{1}{\omega_n^2}\right)\omega^2} \\ 
    &= \dfrac{1}{\left[1-\left(\frac{\omega}{\omega_n}\right)^2 \right] + \complexnum[output-complex-root = j, complex-root-position = before-number, print-complex-unity]{2j}\zeta\left(\frac{\omega}{\omega_n}\right)}
\end{aligned}
$$

### Magnitude

The magnitude of $G(j\omega)$ in $\unit{\decibel}$ is given by

$$
\begin{aligned}
    \abs{G(j\omega)}_{\unit{\decibel}} &= 20\log_{10}\abs{G(j\omega)} = 20\log_{10}\dfrac{1}{\sqrt{\left[1-\left(\dfrac{\omega}{\omega_n}\right)^2 \right]^2 + 4\zeta^2\left(\dfrac{\omega}{\omega_n}\right)^2}} \\
    &= -20\log_{10}\sqrt{\left[1-\left(\dfrac{\omega}{\omega_n}\right)^2 \right]^2 + 4\zeta^2\left(\dfrac{\omega}{\omega_n}\right)^2}
\end{aligned}
$$

Asymptotic approximations to the frequency-response curves are not accurate for a factor with low values of $\zeta$.

This is because the magnitude and phase of the quadratic factor depend on both the corner frequency and the damping ratio $\zeta$.

To obtain the asymptotic frequency-response curve, we consider the two cases as follows:

1.  At very low frequencies such that $\omega \ll \omega_n$, i.e. $\left(\dfrac{\omega}{\omega_n}\right) \ll 1$, then the log magnitude $\abs{G(j\omega)}_{\unit{\decibel}}$ becomes:\
$$
    \abs{G(j\omega)}_{\unit{\decibel}} \cong -20\log_{10}(1) = \SI{0}{\decibel}
$$
The low-frequency asymptote is thus a horizontal line at $\SI{0}{\decibel}$.

2. At very high frequencies such that $\omega \gg \omega_n$, i.e. $\left(\dfrac{\omega}{\omega_n}\right) \gg 1$, then the log magnitude $\abs{G(j\omega)}_{\unit{\decibel}}$ becomes:\
$$
    \abs{G(j\omega)}_{\unit{\decibel}} \cong -20\log_{10}\left(\dfrac{\omega^2}{\omega_n^2}\right) = -40\log_{10}\left(\dfrac{\omega}{\omega_n}\right)
$$
The equation for the high-frequency asymptote is a straight line having the slope $\SI{-40}{\decibel}$/decade.

The high-frequency asymptote intersects the low-frequency asymptote at $\omega = \omega_n$.

This frequency, $\omega_n$, is the corner frequency for the quadratic factor considered.

Note that the two asymptotes just derived are independent of the value of $\zeta$.

Near the frequency $\omega = \omega_n$, a resonant peak occurs.

The damping ratio $\zeta$ determines the magnitude of this resonant peak

There exist errors in the approximation by straight-line asymptotes.

The actual magnitude curve of $G(j\omega)$ differs strikingly from the asymptotic curve. Because, the amplitude and phase curves of the second-order $G(j\omega)$ depend on not only the corner frequency, $\omega_n$, but also on the damping ratio, $\zeta$, which does not enter the asymptotic curve.

The magnitude of the error depends on the value of $\zeta$. It is large for small values of $\zeta$.

### Phase Angle

The phase angle of the quadratic factor $\left[1+2\zeta\left(\dfrac{j\omega}{\omega_n}\right) + \left(\dfrac{j\omega}{\omega_n}\right)^2\right]^{-1}$ is

$$
    \phi = \angle\dfrac{1}{1+2\zeta\left(\dfrac{j\omega}{\omega_n}\right) + \left(\dfrac{j\omega}{\omega_n}\right)^2} = -\tan^{-1}\left[\dfrac{2\zeta \dfrac{\omega}{\omega_n}}{1-\left(\dfrac{\omega}{\omega_n}\right)^2}\right]
$$

The phase angle is a function of both $\omega$ and $\zeta$.

At $\zeta = 0$, the phase angle equals $\SI{0}{\degree}$.

At the corner frequency, $\omega = \omega_n$, the phase angle is $\SI{-90}{\degree}$, regardless of $\zeta$ because

$$
    \phi = -\tan^{-1} \left(\dfrac{2\zeta}{0}\right) = -\tan^{-1} \infty = \SI{-90}{\degree}
$$

i.e. Division by zero leads to tangent of $\infty$.

The Bode plot of the phase angle of the quadratic factor is shown in the figure below.

![Bode Plot of a Quadratic Factor $G(s) = \dfrac{\omega^2}{s^2+2\zeta\omega_n s + \omega_n^2}$]

  [Bode Plot of a Quadratic Factor $G(s) = \dfrac{\omega^2}{s^2+2\zeta\omega_n s + \omega_n^2}$]: ./figures/quad-factor-bode.tex {#fig-bode-plot-quadratic-factor fig-align="center" fig-width="50%"}

## Rules for Drawing Bode Magnitude Plots with Simple Poles and Zeros

- First determine all the break points (pole and zero locations) and arrange in order of increasing frequency.
- Choose a frequency range for the plot that encompasses all these points, adding an extra decade of frequency
above and below this range.
- Based on the poles and zeroes, make a quick sketch of the expected shape of the Bode plot. This will help you find the appropriate vertical scales.
- For a simple pole or zero of the form $(s+a)$, the slope of the uncorrected Bode plot changes at the break point $\omega = a$, increasing by $\SI{20}{\decibel}$/decade for a zero and decreasing by $\SI{20}{\decibel}$/decade for a pole.
- For a repeated pole or zero $(s+a)^r$, the slop changes by $r\times\SI{20}{\decibel}$/decade, or $\SI{20}{\decibel}$ for each time the pole or zero is repeated.
- To find a reference level we first find the behaviour of the function for low frequencies $\omega \to 0$ or high frequencies $\omega \to \infty$. If the limiting behaviour approaches a constant value at these extremes, that is a good starting point. Otherwise we must evaluate the function numerically at some particular frequency, preferably in a region with a constant-value plateau.
- Once the uncorrected Bode plot is finished, a corrected version can be drawn. For simple/repeated roots the true
response passes through a point that is $r\times\SI{3}{\decibel}$ below the uncorrected curve at the break point, or $\SI{3}{\decibel}$ for each time the pole or zero is repeated.

## Relative Stability Analysis Using Bode Plots

Motivation: Stability is paramount.

- In practice it is not enough that a system is stable due to modelling uncertainties
- There must also be some margins of stability that describe how stable the system is
- We shall concentrate on minimum phase systems
- In time-domain, the closer the dominant closed-loop poles are to the imaginary axis, the poorer the system's relative stability.

## Measures of Relative Stability

**__Gain Crossover Frequency__**

The frequency at which the magnitude of the open-loop transfer function gain ($\abs{G(j\omega)}$) is unity or $\SI{0}{\decibel}$ is called the *Gain Cross Over Frequency*. It is denoted by $\omega_{gc}$.

**__Phase Crossover Frequency__**

The frequency at which the phase angle of the open loop transfer function ($\angle G(j\omega)$) equals $-\SI{180}{\degree}$ is called the *Phase Cross Over Frequency*. It is denoted by $\omega_{pc}$.

**__Gain Margin__**

It is the amount of gain that can be allowed to increase -- in the loop -- at the phase crossover frequency, before the closed-loop system reaches instability.

In other words, the gain margin is the reciprocal of the magnitude $\abs{G(j\omega)}$ at the frequency at which the phase angle is $-\SI{180}{\degree}$, i.e. at the phase crossover frequency, $\omega_{pc}$. If $K_g$ denotes the gain margin of the system. Then

$$
    K_g = \dfrac{1}{\abs{G(j\omega_{pc})}}\qcomma K_g \unit{\decibel} = 20\log_{10} K_g = -20\log_{10}\abs{G(j\omega_{pc})}
$$

The gain margin expressed in decibels, is positive if $K_g$ is greater than unity, and negative if $K_g$ is smaller than unity.

Thus, a positive gain margin (in decibels) means that the system is stable, and a negative gain margin (in decibels) means that the system is unstable.

For a stable minimum-phase system, the gain margin indicates how much the gain can be increased before the system becomes unstable. For an unstable system, the gain margin is indicative of how much the gain must be decreased to make the system stable.

**__Phase Margin__**

The phase margin is the amount of additional phase lag at the gain crossover frequency required to bring the system to the verge of instability.

The phase margin $\gamma$ is $\SI{180}{\degree}$ plus the phase angle $\phi_{gc}$ (in degrees) of the open-loop transfer function at the gain crossover frequency, or

$$
    \gamma = 180 + \phi_{gc}
$$

<!-- !figures skipped -->


## Frequency Domain Stability: Summary

The stability of the control system based on the relation between the phase cross over frequency and the gain cross over frequency is listed below

1. If the phase cross over frequency $\omega_{pc}$ is greater than the gain cross over frequency $\omega_{gc}$, (i.e. $\omega_{pc} > \omega_{gc}$), the control system is stable.
2. If the phase cross over frequency $\omega_{pc}$ is equal to the gain cross over frequency $\omega_{gc}$, (i.e. $\omega_{pc} = \omega_{gc}$), the control system is marginally stable.
3. If the phase cross over frequency $\omega_{pc}$ is less than the gain cross over frequency $\omega_{gc}$, (i.e. $\omega_{pc} < \omega_{gc}$), the control system is unstable.

The stability of the control system based on the relation between gain margin and phase margin is listed below.

1. If both the gain margin, GM, amd the phase margin, PM, are positive, then the control system is stable.
2. If both the gain margin, GM, and the phase margin, PM, are equal to zero, then the control system is marginally stable.
3. If the gain margin, GM, and/or the phase margin, PM, are/is negative, then the control system is unstable. 