project: 
  type: book
include-in-header: 
 - preamble.tex
filters: 
  - color-filter
  - latex-environment
 
environments:
  - tcolorbox

  

book:
  chapters:
    - index.qmd
    - part: "Lectures 1 - 3"
      chapters:
        - lecture1-3/01-introduction.qmd
        - lecture1-3/02-basics-of-computer-architecture.qmd
        - lecture1-3/03-ISAs.qmd

title: "COMPSYS 304: Computer Architecture"
subtitle: "Lecture Notes"
author: "Nicholas Russell"
date: "3/09/2024"
format:
  pdf:
    pdf-engine: latexmk
    pdf-engine-opts: 
      - "-synctex=1"
      - "-interaction=nonstopmode"
      - "-file-line-error"
      - "-lualatex"
      - "-shell-escape"
    geometry: 
      - "top=2cm"
      - "bottom=2cm"
      - "left=1.5cm"
      - "right=1.5cm"
      - "marginparsep=2cm"
    toc: true
    toc-depth: 3
    number-sections: true
    keep-tex: true
    keep-md: true
    hyperrefoptions: 
      - "pdfpagelabels"
    documentclass: report
    fontsize: 12pt
    papersize: a4
    css-property-processing: translate




