project:
  type: book
include-in-header:
  - preamble.tex
filters:
  - color-filter
  - latex-environment
environments:
  - tcolorbox
book:
  chapters:
    - index.qmd
    - part: "Lectures 1 - 3"
      chapters:
        - lecture1-3/01-introduction.qmd
        - lecture1-3/02-basics-of-computer-architecture.qmd
        - lecture1-3/03-ISAs.qmd
        - lecture1-3/04-ISA-design.qmd

title: "COMPSYS 304: Computer Architecture"
subtitle: "Lecture Notes"
author: "Nicholas Russell"
date: 09/03/2024
date-format: full
format:
  pdf:
    pdf-engine: latexmk
    pdf-engine-opts:
      - "-synctex=1"
      - "-interaction=nonstopmode"
      - "-file-line-error"
      - "-lualatex"
      - "-shell-escape"
    toc: true
    toc-depth: 3
    number-sections: true
    keep-tex: true
    keep-md: true
    hyperrefoptions:
      - "pdfpagelabels"
    documentclass: scrreprt
    fontsize: 14pt
    papersize: a4
    pagestyle: plain
    classoption:
      - headinclude=true
      - footinclude=true
    geometry:
      - "top=2.5cm"
      - "bottom=2.5cm"
      - "left=1.5cm"
      - "right=1.5cm"
      - "marginparsep=2cm"
    fontfamily: lmodern