::: {#topic1}
## Topic 1: The Importance of the Exponential Function

The Exponential function, written as either $e^{ax}$ or $e^{at}$ depending on whether it is $f(t)$ or $f(x)$, has properties that make it mathematically unique.

1.  The derivative (rate of change) of the exponential function is the exponential function itself. More generally, this is a function whose rate of change is proportional to the function itself.

    ::: {#exp-derivative}
    \begin{equation} 
    \label{eq:exp-derivative}     
    \dv{e^{ax}}{x} = a e^{ax} 
    \end{equation}
    :::

2.  The integral of the exponential function is also the exponential function itself.

    ::: {#exp-integral}
    \begin{equation} 
    \label{eq:exp-integral}     
    \int e^{ax} \dd{x} = \frac{1}{a} e^{ax} \end{equation}
    :::
:::

:::: {#topic2}
## Topic 2: The Concept of Engineering Infinity

Consider a signal $e^{-at}$. The time constant for this signal is $T = \frac{1}{a}$. Theoretically, the signal is meant to decay to zero as time approaches infinity, i.e.

::: {#engineering-infinity}
\begin{equation} 
\label{eq:eng-infinity}     
\lim_{t \to \infty} e^{-at} = 0  \end{equation}
:::

But in practice, this is not the case, as its value will be very, very small after five time constants $5T$ (or $5\tau$). This is the \textcolor{red}{\textbf{\textit{Concept of Engineering Infinity}}}. The signal will never reach zero, but it will be so small that it can be considered zero for all practical purposes. This is a very important concept in control systems, as it allows us to simplify our calculations and analysis.
::::