## Topic 4: What are Signals?
### Introduction
```{=latex}
%| label: signal-def
It is difficult to find a unique definition of a signal. However in the context of this course, we give a workable definition which suits most of out purposes as:\\
\begin{tcolorbox}[colback=boxbodycol,colframe=boxheadcol]
    \begin{center}
        \textcolor{red}{\emph{A Signal conveys information about a physical phenomenon which evolves in time or space.}}
    \end{center}
\end{tcolorbox}
```
Examples of such signals include: Voltage, Current, Speech, Television, Images from remote space probes, Voltages generated by the heart and brain, Radar and Sonar echoes, Seismic vibrations, Signals from GPS satellites, Signals from human genes, and countless other applications.

### Energy and Power Signals
```{=latex}
\begin{tcolorbox}[colback=boxbodycol, colframe=boxheadcol, title=\bluetext{\textbf{Energy Signals}}]\label{fig:energy-signal-def-tcbox}
    \begin{center}
        \textcolor{red}{A signal is said to be an \emph{energy signal} if and only if it has finite energy.}
    \end{center}
\end{tcolorbox}
\begin{tcolorbox}[colback=boxbodycol, colframe=boxheadcol, title=\textcolor{red}{\textbf{Power Signals}}]\label{fig:power-signal-def-tcbox}
    \begin{center}
        \bluetext{A signal is said to be a \emph{power signal} if and only if the average power of the signal is finite and non-zero.}
    \end{center}
\end{tcolorbox}
\begin{tcolorbox}[colback=boxbodycol, colframe=boxheadcol, title=\textcolor{red}{\textbf{Instantaneous Power}}]\label{fig:instantaneous-power-def}
The instantaneous power \(p(t)\) of a signal \(x(t)\) is expressed as:
    \begin{equation}
        \label{eq:instantaneous-power-def}
        \textcolor{red}{p(t) = x^2(t)}
    \end{equation}
\end{tcolorbox}
\begin{tcolorbox}[colback=boxbodycol, colframe=boxheadcol, title=\textcolor{red}{\textbf{Continuous-Time Signal Energy}}]\label{fig:continuous-time-energy-def}
The total energy of a continuous-time signal \(x(t)\) is given by:
    \begin{equation}
        \label{eq:continuous-time-energy-def}     
        \bluetext{E = \lim_{T \to \infty}\int_{-T/2}^{T/2} x^2(t) \dd{t} = \int_{-\infty}^{\infty} x^2(t) \dd{t}} 
    \end{equation}
\end{tcolorbox}
\begin{tcolorbox}[colback=boxbodycol, colframe=boxheadcol, title=\textcolor{red}{\textbf{Complex Valued Signal Energy}}]\label{fig:complex-signal-energy-def}
For a complex valued signal:
    \begin{equation}
        \label{eq:complex-signal-energy-def}
        \textcolor{red}{E = \int_{-\infty}^{\infty} \abs{x(t)}^2 \dd{t}} 
    \end{equation}
\end{tcolorbox}
\begin{tcolorbox}[colback=boxbodycol, colframe=boxheadcol, title=\textcolor{red}{\textbf{Average Power}}]\label{fig:average-power-def}
Since power equals to the time average of the energy, the average power is given by:
    \begin{equation}     
        \label{eq:average-power-def}     
        \textcolor{blue}{P = \lim_{T \to \infty} \frac{1}{T} \int_{-T/2}^{T/2} x^2(t) \dd{t} = \frac{E}{T}}
    \end{equation}
\end{tcolorbox}
```

```{=latex}
%| label: energy-power-relationship
Note that during calculation of energy, we average the power over an indefinitely large interval.\\ \begin{tcolorbox}[colback=boxbodycol,colframe=boxheadcol]\label{fig:energy-power-relationship-1}     
    \begin{center}         
        \textcolor{red}{A signal with finite energy has zero power and a signal with finite power has infinite energy.}     
    \end{center} 
\end{tcolorbox}
```

```{=latex}
%| label: energy-power-relationship-itemize
Furthermore, some additional concepts of note:\\ 
\begin{tcolorbox}[colback=boxbodycol,colframe=boxheadcol]
\label{fig:energy-power-relationship-itemize}
    \begin{center}
        \begin{itemize}             
            \item[\bluetext{a.}] A signal \textcolor{red}{can not both be an energy and a power signal.} This classification of signals based on power and energy are \textcolor{red}{mutually exclusive.}             
            \item[\bluetext{b.}] However, \bluetext{a signal can belong to neither of the above two categories.}             
            \item[\bluetext{c.}] The signals which are both deterministic and non-periodic have finite energy and therefore are energy signals.\,\textcolor{red}{Most of the signals, in practice, belong to this category.}             
            \item[\bluetext{d.}] \bluetext{Periodic signals and random signals} are essentially \textcolor{red}{power signals.}             
            \item[\bluetext{e.}] Periodic signals for which the area under \(\abs{x(t)}^2\) over one period is finite are power signals.         
        \end{itemize}     
    \end{center} 
\end{tcolorbox}
```

### Examples

#### Example 1: Unit Step Function

Consider a unit step function defined as:

```{=latex}
%| label: unit-step-function-example
\begin{equation}
    \label{eq:unit-step-function-example}     
    \bluetext{u(t) =         
        \begin{cases}             
        1 & t \geq 0         \\             
        0 & \text{otherwise}         
        \end{cases}} 
\end{equation}
```

Determine whether this is an energy signal or a power signal or neither.

**Solution:** Let us compute the energy of this signal as:

```{=latex}
%| label: unit-step-energy
\begin{equation}     
    \label{eq:unit-step-energy}     
    E = \int_{-\infty}^{\infty} {[u(t)]}^2 \dd{t} = \int_{0}^{\infty} {[0]}^2 \dd{t} = \int_{0}^{\infty} {[1]}^2 \dd{t} = \infty 
\end{equation}
```

Since the energy of this signal is infinite, it cannot be an energy signal. Let us compute the power of this signal as:

```{=latex}
%| label: unit-step-power
\begin{equation}     
    \label{eq:unit-step-power}     
    \bluetext{P = \lim_{T \to \infty} \frac{1}{T} \int_{-T/2}^{T/2} {[u(t)]}^2 \dd{t} = \lim_{T \to \infty} \frac{1}{T} \int_{0}^{T/2} {[u(t)]}^2 \dd{t} = \frac{1}{2}} 
\end{equation}
```

The power of this signal is finite. Hence, $\textcolor{red}{\text{this is a power signal.}}$

#### Example 2: Exponential Function 

Consider an exponential function defined as:

```{=latex}
%| label: exponential-function-example
\begin{equation}     
\label{eq:exponential-function-example}
    x(t) = e^{-at}u(t), \, \text{where} \; u(t) \;\text{is the unit step signal},\, a > 0 
\end{equation}
```

Classify this signal as an energy, power, or neither.

**Solution:** Let us compute the energy of this signal as:

```{=latex}
%| label: exp-function-energy
\begin{equation}     
\label{eq:exp-function-energy}     
E = \int_{-\infty}^{\infty} {[x(t)]}^2  \dd{t} = \int_{0}^{\infty} {[e^{-at}]}^2 \dd{t} = \int_{0}^{\infty} e^{-2at} \dd{t} = \frac{1}{2a} < \infty 
\end{equation}
```

Thus, $x(t) = e^{-at} u(t)$ is an $\textcolor{red}{\text{energy signal}}$.

#### Example 3: Ramp Function: 

Consider a ramp function defined as:

```{=latex}
%| label: ramp-function-example
\begin{equation}     
\label{eq:ramp-function-example}     
r(t) = 
    \begin{cases}         
        At & t \geq 0         \\         
        0  & \text{otherwise}     
    \end{cases} 
\end{equation}
```


Classify this signal as an energy, power, or neither.

**Solution:** Let us compute the energy of this signal as:


```{=latex}
%| label: ramp-function-energy
\begin{equation}     
\label{eq:ramp-function-energy}     
E = \int_{-\infty}^{\infty} {r(t)}^2 \dd{t} = \int_{-\infty}^{0} {[0]}^2 \dd{t} = \int_{0}^{\infty} A^2 t^2 \dd{t} = A^2 \frac{T^3}{3} \Bigg|_{0}^{\infty} = \infty 
\end{equation}
```

Since the energy of this signal is infinite, it cannot be an energy signal. Let us compute the power of this signal as:

```{=latex}
%| label: ramp-function-power
\begin{equation}     
\label{eq:ramp-function-power}     
P = \lim_{T \to \infty} \frac{1}{T} \int_{-T/2}^{T/2} {[r(t)]}^2 \dd{t} = \lim_{T \to \infty} \frac{1}{T} \int_{0}^{T/2} A^2 t^2 \dd{t} = A^2 \lim_{T \to \infty} \frac{1}{T} \frac{T^3}{3} \Bigg|_{0}^{\infty} = \infty 
\end{equation} 
```

The power of this signal is infinite. Hence, this is $\textcolor{red}{\text{neither a power nor an energy signal.}}$.