project:
  title: "COMPSYS 304"

title: "COMPSYS 304"
subtitle: "Lecture Notes"
author:
    name: Nicholas Russell
    affiliations:
      - name: University of Auckland
        department: Department of Electrical, Computer, and Software Engineering

format:
  titlepage-pdf:
    pdf-engine: latexmk
    pdf-engine-opts:
      - "-synctex=1"
      - "-interaction=nonstopmode"
      - "-file-line-error"
      - "-lualatex"
      - "-shell-escape"
    number-sections: true
    toc: true
    top-level-division: section
    classoption: ["oneside", "open=any", "a4paper", "12pt"]
    hyperrefoptions:
      - "pdfpagelabels"
    documentclass: article
    papersize: a4
    pagestyle: plain
    fontsize: 12pt
    geometry:
      - "top=2.5cm"
      - "bottom=2.5cm"
      - "left=1cm"
      - "right=1cm"
      - "marginparsep=2cm"
    fontfamily: lmodern
    latex-clean: true
    titlepage: academic
    titlepage-logo: "img/DECSE-HC-4C-01.png"
    titlepage-theme:
      logo-size: "0.8\\textwidth"
      author-fontstyle: "large"
      author-style: author-address
      author-space-after: "1cm"
      affiliation-sep: "newline"